name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check SSH Key
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "❌ SSH_PRIVATE_KEY is not set!"
            exit 1
          else
            echo "✅ SSH_PRIVATE_KEY is configured"
          fi
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 51.210.244.26
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "✅ Connexion SSH réussie!"
            cd /var/www/storal.fr
            git fetch origin && git reset --hard origin/main
            pm2 restart all
            echo "✅ Déploiement terminé!"
